server:
  port: 8080

spring:
  data:
    redis:
      host: ${SPRING_REDIS_HOST:redis}
      port: ${SPRING_REDIS_PORT:6379}

ironpdf:
  license:
    cron: "0 0 2 * * *"
    key: ${IRONPDF_LICENSE_KEY:IRONSUITE.TKENNEDY2605.GMAIL.COM.25078-869803150C-DSFSJ3G-STZ5Z4OEPWEJ-S7AS4FL75DPG-D67HG5B2W7IQ-IDYBF6Y6CS3K-PQFAYDTYDJG7-46N5FJFYXUCL-VBAPLX-TB6YPZVELXWPEA-DEPLOYMENT.TRIAL-ZQYSFN.TRIAL.EXPIRES.21.MAY.2025}
